#!/usr/bin/env perl

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/extlib/lib/perl5";
use lib "$FindBin::Bin/lib";
use Getopt::Long qw(:config posix_default no_ignore_case gnu_compat);
use Urume::DnsmasqAgent;

my ($redis_server, $config, $command);
GetOptions(
    "redis|r=s"           => \$redis_server,
    "file|f=s"            => \$config,
    "restart-command|c=s" => \$command,
);
my $agent = Urume::DnsmasqAgent->new({
    redis => {
        server    => $redis_server,
        reconnect => 1,
    },
    config          => $config,
    restart_command => $command,
});
$agent->run;
