#!/usr/bin/env perl

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/extlib/lib/perl5";
use lib "$FindBin::Bin/lib";
use Getopt::Long qw(:config posix_default no_ignore_case gnu_compat);
use Urume::HostAgent;

my ($redis_server, $host, $timeout, $dir);
GetOptions(
    "redis|r=s"      => \$redis_server,
    "images_dir|d=s" => \$dir,
    "host|h=s"       => \$host,
    "timeout|t=i"    => \$timeout,
);
my $config = {
    host => $host,
    images_dir => $dir,
    timeout    => $timeout,
    redis => {
        server    => $redis_server,
        reconnect => 1,
    },
};
my $agent = Urume::HostAgent->new($config);
$agent->run;
